/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import GestionArchivos.GuardarResumenes;
import static Interfaces.Bienvenido.sistemaInv;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cargarR = new javax.swing.JButton();
        analizarR = new javax.swing.JButton();
        buscarR = new javax.swing.JButton();
        buscarRa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        cargarR.setText("Cargar Resumen");
        cargarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarRActionPerformed(evt);
            }
        });
        jPanel1.add(cargarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, -1));

        analizarR.setText("Analizar Resumen");
        analizarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarRActionPerformed(evt);
            }
        });
        jPanel1.add(analizarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, -1));

        buscarR.setText("Buscar Palabra Clave");
        buscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRActionPerformed(evt);
            }
        });
        jPanel1.add(buscarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, -1));

        buscarRa.setText("Buscar por Autor");
        buscarRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRaActionPerformed(evt);
            }
        });
        jPanel1.add(buscarRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 160, -1));

        jButton1.setText("Listar Palabras Clave");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 350, -1));

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarRActionPerformed
        CargarArchivo cargarA = new CargarArchivo();
        this.dispose();
    }//GEN-LAST:event_cargarRActionPerformed

    private void analizarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarRActionPerformed
        AnalizaResumen analizar = new AnalizaResumen();
        this.dispose();
    }//GEN-LAST:event_analizarRActionPerformed

    private void buscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRActionPerformed
        BuscarPalabraClave buscarA = new BuscarPalabraClave();
        this.dispose();
    }//GEN-LAST:event_buscarRActionPerformed

    private void buscarRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRaActionPerformed
        BuscarAutor buscarAutor = new BuscarAutor();
        this.dispose();
    }//GEN-LAST:event_buscarRaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListarPalabras listarP = new ListarPalabras();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GuardarResumenes guardar = new GuardarResumenes(sistemaInv);
        guardar.guardarEnTest("resumenes");
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizarR;
    private javax.swing.JButton buscarR;
    private javax.swing.JButton buscarRa;
    private javax.swing.JButton cargarR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
